//CONST USER
export const AUTHETICATE_USER = 'AUTHETICATE_USER';
export const CREATE_USER = 'CREATE_USER'
export const LOAD_USER = 'LOAD_USER'
export const SUCCESS_USER = 'SUCCESS_USER'
export const ERROR_USER = 'ERROR_USER'

// CONST ANIMAL
export const FETCH_ANIMALS = 'FETCH_ANIMALS'
export const CREATE_ANIMAL = 'CREATE_ANIMAL'
export const SUCESS_ANIMALS = 'SUCESS_ANIMALS'
export const LOAD_ANIMALS  = 'LOAD_ANIMALS'
export const ERROR_ANIMALS  = 'ERROR_ANIMALS'

//CONST PESSOAS
export const CREATE_PESSOA = 'CREATE_PESSOA'
export const SUCESS_PESSOA = 'SUCESS_PESSOA'
export const LOAD_PESSOA = 'LOAD_PESSOA'
export const ERROR_PESSOA  = 'ERROR_PESSOA'